### PR TITLE
Zbolian/init scraper and etl

### PR DESCRIPTION
**Pull request by zachbolian**
@dnwarnock - here's my code. Thing are kept in separate directories. How do you feel about moving all of your stuff inside another directory `app` or something like that? I think that kinda organizes our code like we've organized the steps in our write ups. We'll have to summarize our various readmes into a master readme in the root dir per the instructions, but that shouldn't be hard. Just some copy/paste then refer to subdirectory readme for more detail.

### CODE REVIEW

**Comment by zachbolian** [comment]
Actually just noticed were supposed to pull ALL code inside a subdir called `CODE` and then submit our poster and write up in another subdir called `DOC`. So particular these folks...

**Comment by dnwarnock** [comment]
@zachbolian Do you mind just adding to the .gitignore that already in the project? I'll merge after that

**Comment by zachbolian** [comment]
@dnwarnock - done

**Comment by zachbolian** [comment]
Also just added a dedupe function to get rid of dupes. Seems like lists for google maps and zillow weren't fully mutually exclusive then they were cartesianing.

**Pull request merged**
